# Generated by Django 5.2.8 on 2025-11-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='native_to',
            field=models.ManyToManyField(blank=True, related_name='plants', to='plants.countries'),
        ),
    ]
