# Generated by Django 5.2.8 on 2025-11-25 06:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_plant_native_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
