# Generated by Django 5.2.8 on 2025-11-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0008_contact_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
